### ISSUE TITLE
Question about extracted vox files

### ISSUE THREAD

**Issue by bbfe** [bentorkington/cps1-sound-extract#2]
I can load the vox files in Audacity to convert them to something like wav, but can you tell me what the correct sample rate to use for CPS1 games is?

If I use VOX ADPCM encoding, little-endian byte order, 1 channel mono, and a sample rate of 7575hz, it seems to more or less sound normal, but is that right?

**Comment by bentorkington** [comment]
7575.7 Hz to be precise

**Comment by bbfe** [comment]
So if I'm converting the vox files to wav, would 7576hz be the best sample rate option to get as close as possible to native?

**Comment by bentorkington** [comment]
If you think anyone will notice a 0.001% speed-up, which they won't.

Please don't abuse my issue tracker for Q&A. There is an entire community of emulators/reverse engineering fans, your questions would be better posted on Stack Exchange or even Reddit where everyone will be able to help you.
